# Generated by Django 3.2.9 on 2022-02-01 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20220201_2251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='cat_options',
        ),
        migrations.RemoveField(
            model_name='category',
            name='friendly_name',
        ),
        migrations.AddField(
            model_name='category',
            name='category_options',
            field=models.CharField(blank=True, choices=[('Games', 'Games'), ('Consoles', 'Consoles'), ('Accessories', 'Accessories'), ('All Products', 'All Products')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='promotion',
            name='name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
