# Generated by Django 3.2.9 on 2022-02-02 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20220202_1617'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={},
        ),
        migrations.AlterField(
            model_name='category',
            name='friendly_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='default', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='genre',
            name='friendly_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(default='default', max_length=100, null=True),
        ),
    ]
